[package]
name = "hc20"
version = "0.1.0"
authors = ["Stefan Andreas Baur <stefan_andreas.baur@daimler.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
rayon = "1.1"